# Generated by Django 3.2.5 on 2023-08-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynote', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='des',
        ),
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
