# Generated by Django 3.2.5 on 2023-08-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynote', '0002_auto_20230807_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='age',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='name1',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
